from typing import Dict, List, Set

ENGINE_VERSION = "drug_safety_rules_v2"

CRITICAL_CONSEQUENCE_KEYWORDS = {
    "bleeding",
    "haemorrhage",
    "hemorrhage",
    "arrhythmia",
    "torsades",
    "ventricular",
    "qt prolongation",
    "seizure",
    "seizures",
    "organ failure",
    "serotonin syndrome",
    "cardiac arrest",
    "hyperkalemia",
    "hyperkalaemia",
    "toxicity",
    "respiratory depression",
    "hypoglycemia",
    "hypoglycaemia",
    "lactic acidosis",
    "aki",
    "acute kidney injury",
    "hypertensive crisis",
    "hypotension",
    "cardiovascular collapse",
    "pancytopenia",
}

ONTOLOGY_SYNONYMS: Dict[str, str] = {
    "warfarin sodium": "warfarin",
    "coumadin": "warfarin",
    "jantoven": "warfarin",
    "acetylsalicylic acid": "aspirin",
    "asa": "aspirin",
    "ecotrin": "aspirin",
    "disprin": "aspirin",
    "glycopyrrolate": "glycopyrronium",
    "adrenaline": "epinephrine",
    "noradrenaline": "norepinephrine",
    "levophed": "norepinephrine",
    "vasopressin": "vasopressin",
    "ibuprofen sodium": "ibuprofen",
    "advil": "ibuprofen",
    "nurofen": "ibuprofen",
    "motrin": "ibuprofen",
    "naproxen sodium": "naproxen",
    "aleve": "naproxen",
    "naprosyn": "naproxen",
    "diclofenac sodium": "diclofenac",
    "voltaren": "diclofenac",
    "celecoxib": "celecoxib",
    "metformin hydrochloride": "metformin",
    "glucophage": "metformin",
    "fortamet": "metformin",
    "fentanyl citrate": "fentanyl",
    "duragesic": "fentanyl",
    "sublimaze": "fentanyl",
    "morphine sulfate": "morphine",
    "morphine sulphate": "morphine",
    "ms contin": "morphine",
    "oxycodone hydrochloride": "oxycodone",
    "oxycontin": "oxycodone",
    "percocet": "oxycodone",
    "hydromorphone hydrochloride": "hydromorphone",
    "dilaudid": "hydromorphone",
    "tramadol hydrochloride": "tramadol",
    "ultram": "tramadol",
    "codeine phosphate": "codeine",
    "methadone hydrochloride": "methadone",
    "pethidine": "pethidine",
    "meperidine": "pethidine",
    "buprenorphine hydrochloride": "buprenorphine",
    "subutex": "buprenorphine",
    "tapentadol hydrochloride": "tapentadol",
    "fluoxetine hydrochloride": "fluoxetine",
    "prozac": "fluoxetine",
    "sarafem": "fluoxetine",
    "sertraline hydrochloride": "sertraline",
    "zoloft": "sertraline",
    "lustral": "sertraline",
    "citalopram hydrobromide": "citalopram",
    "celexa": "citalopram",
    "escitalopram oxalate": "escitalopram",
    "lexapro": "escitalopram",
    "cipralex": "escitalopram",
    "paroxetine hydrochloride": "paroxetine",
    "paxil": "paroxetine",
    "phenelzine sulfate": "phenelzine",
    "nardil": "phenelzine",
    "tranylcypromine": "tranylcypromine",
    "parnate": "tranylcypromine",
    "selegiline hydrochloride": "selegiline",
    "eldepryl": "selegiline",
    "moclobemide": "moclobemide",
    "linezolid": "linezolid",
    "zyvox": "linezolid",
    "amiodarone hydrochloride": "amiodarone",
    "cordarone": "amiodarone",
    "pacerone": "amiodarone",
    "digoxin": "digoxin",
    "lanoxin": "digoxin",
    "verapamil hydrochloride": "verapamil",
    "isoptin": "verapamil",
    "calan": "verapamil",
    "lisinopril": "lisinopril",
    "zestril": "lisinopril",
    "prinivil": "lisinopril",
    "ramipril": "ramipril",
    "altace": "ramipril",
    "enalapril maleate": "enalapril",
    "vasotec": "enalapril",
    "losartan potassium": "losartan",
    "cozaar": "losartan",
    "valsartan": "valsartan",
    "diovan": "valsartan",
    "irbesartan": "irbesartan",
    "spironolactone": "spironolactone",
    "aldactone": "spironolactone",
    "furosemide": "furosemide",
    "frusemide": "furosemide",
    "lasix": "furosemide",
    "metoprolol succinate": "metoprolol",
    "metoprolol tartrate": "metoprolol",
    "lopressor": "metoprolol",
    "toprol": "metoprolol",
    "atenolol": "atenolol",
    "tenormin": "atenolol",
    "propranolol hydrochloride": "propranolol",
    "inderal": "propranolol",
    "carvedilol": "carvedilol",
    "coreg": "carvedilol",
    "bisoprolol fumarate": "bisoprolol",
    "haloperidol decanoate": "haloperidol",
    "haldol": "haloperidol",
    "midazolam hydrochloride": "midazolam",
    "versed": "midazolam",
    "diazepam": "diazepam",
    "valium": "diazepam",
    "lorazepam": "lorazepam",
    "ativan": "lorazepam",
    "clonazepam": "clonazepam",
    "klonopin": "clonazepam",
    "alprazolam": "alprazolam",
    "xanax": "alprazolam",
    "propofol": "propofol",
    "diprivan": "propofol",
    "ketamine hydrochloride": "ketamine",
    "dexmedetomidine hydrochloride": "dexmedetomidine",
    "precedex": "dexmedetomidine",
    "heparin sodium": "heparin",
    "unfractionated heparin": "heparin",
    "ufh": "heparin",
    "enoxaparin sodium": "enoxaparin",
    "lovenox": "enoxaparin",
    "clexane": "enoxaparin",
    "dalteparin sodium": "dalteparin",
    "fragmin": "dalteparin",
    "tinzaparin sodium": "tinzaparin",
    "fondaparinux sodium": "fondaparinux",
    "arixtra": "fondaparinux",
    "dabigatran etexilate": "dabigatran",
    "pradaxa": "dabigatran",
    "rivaroxaban": "rivaroxaban",
    "xarelto": "rivaroxaban",
    "apixaban": "apixaban",
    "eliquis": "apixaban",
    "edoxaban": "edoxaban",
    "savaysa": "edoxaban",
    "clopidogrel bisulfate": "clopidogrel",
    "plavix": "clopidogrel",
    "ticagrelor": "ticagrelor",
    "brilinta": "ticagrelor",
    "prasugrel": "prasugrel",
    "effient": "prasugrel",
    "glycoprotein iib iiia": "gp iib/iiia inhibitor",
    "abciximab": "abciximab",
    "reopro": "abciximab",
    "eptifibatide": "eptifibatide",
    "integrilin": "eptifibatide",
    "tirofiban": "tirofiban",
    "aggrastat": "tirofiban",
    "sildenafil citrate": "sildenafil",
    "viagra": "sildenafil",
    "revatio": "sildenafil",
    "tadalafil": "tadalafil",
    "cialis": "tadalafil",
    "glyceryl trinitrate": "nitroglycerin",
    "gtn": "nitroglycerin",
    "nitroglycerine": "nitroglycerin",
    "isosorbide mononitrate": "isosorbide",
    "isosorbide dinitrate": "isosorbide",
    "imdur": "isosorbide",
    "omeprazole magnesium": "omeprazole",
    "prilosec": "omeprazole",
    "losec": "omeprazole",
    "esomeprazole magnesium": "esomeprazole",
    "nexium": "esomeprazole",
    "pantoprazole sodium": "pantoprazole",
    "protonix": "pantoprazole",
    "metronidazole": "metronidazole",
    "flagyl": "metronidazole",
    "fluconazole": "fluconazole",
    "diflucan": "fluconazole",
    "clarithromycin": "clarithromycin",
    "biaxin": "clarithromycin",
    "azithromycin dihydrate": "azithromycin",
    "zithromax": "azithromycin",
    "z-pak": "azithromycin",
    "ciprofloxacin hydrochloride": "ciprofloxacin",
    "cipro": "ciprofloxacin",
    "levofloxacin": "levofloxacin",
    "levaquin": "levofloxacin",
    "moxifloxacin hydrochloride": "moxifloxacin",
    "avelox": "moxifloxacin",
    "vancomycin hydrochloride": "vancomycin",
    "vancocin": "vancomycin",
    "gentamicin sulfate": "gentamicin",
    "garamycin": "gentamicin",
    "tobramycin sulfate": "tobramycin",
    "amikacin sulfate": "amikacin",
    "piperacillin-tazobactam": "piperacillin-tazobactam",
    "pip-tazo": "piperacillin-tazobactam",
    "pip/tazo": "piperacillin-tazobactam",
    "zosyn": "piperacillin-tazobactam",
    "tazocin": "piperacillin-tazobactam",
    "meropenem trihydrate": "meropenem",
    "merrem": "meropenem",
    "imipenem-cilastatin": "imipenem",
    "primaxin": "imipenem",
    "valproic acid": "valproate",
    "valproate sodium": "valproate",
    "sodium valproate": "valproate",
    "depakote": "valproate",
    "epilim": "valproate",
    "phenytoin sodium": "phenytoin",
    "dilantin": "phenytoin",
    "methotrexate sodium": "methotrexate",
    "rheumatrex": "methotrexate",
    "trexall": "methotrexate",
    "lithium carbonate": "lithium",
    "lithium citrate": "lithium",
    "eskalith": "lithium",
    "lithobid": "lithium",
    "regular insulin": "insulin",
    "insulin glargine": "insulin",
    "insulin detemir": "insulin",
    "insulin lispro": "insulin",
    "insulin aspart": "insulin",
    "insulin degludec": "insulin",
    "novorapid": "insulin",
    "humalog": "insulin",
    "lantus": "insulin",
    "toujeo": "insulin",
    "potassium chloride": "potassium chloride",
    "kcl": "potassium chloride",
    "kay ciel": "potassium chloride",
    "cyclophosphamide": "cyclophosphamide",
    "cytoxan": "cyclophosphamide",
    "vincristine sulfate": "vincristine",
    "oncovin": "vincristine",
    "doxorubicin hydrochloride": "doxorubicin",
    "adriamycin": "doxorubicin",
    "cisplatin": "cisplatin",
    "platinol": "cisplatin",
    "carboplatin": "carboplatin",
    "paraplatin": "carboplatin",
    "fluorouracil": "fluorouracil",
    "5-fu": "fluorouracil",
    "capecitabine": "capecitabine",
    "xeloda": "capecitabine",
}

INTERACTION_PAIRS: List[Dict] = [
    {
        "drugs": {"warfarin", "aspirin"},
        "mechanism": "Additive anticoagulation and platelet inhibition",
        "consequence": "Major bleeding risk; GI haemorrhage or intracranial bleeding",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid combination unless benefit clearly outweighs risk", "Monitor INR closely", "Consider PPI gastroprotection if combination is unavoidable"],
    },
    {
        "drugs": {"warfarin", "ibuprofen"},
        "mechanism": "NSAID inhibits platelet aggregation and displaces warfarin from plasma proteins",
        "consequence": "Major bleeding risk",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid NSAIDs in patients on warfarin", "Use paracetamol for analgesia"],
    },
    {
        "drugs": {"warfarin", "naproxen"},
        "mechanism": "NSAID inhibits platelet aggregation and displaces warfarin from plasma proteins",
        "consequence": "Major bleeding risk",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid NSAIDs in patients on warfarin", "Use paracetamol for analgesia"],
    },
    {
        "drugs": {"warfarin", "diclofenac"},
        "mechanism": "NSAID inhibits platelet aggregation; diclofenac inhibits CYP2C9",
        "consequence": "Major bleeding risk and elevated INR",
        "severity": "CRITICAL",
        "interaction_class": "PK",
        "confidence_level": "HIGH",
        "evidence_source": "pharmacology_db",
        "actions": ["Avoid combination", "Monitor INR urgently if already co-prescribed"],
    },
    {
        "drugs": {"warfarin", "fluconazole"},
        "mechanism": "Fluconazole inhibits CYP2C9, reducing warfarin metabolism",
        "consequence": "Supratherapeutic INR leading to bleeding",
        "severity": "CRITICAL",
        "interaction_class": "PK",
        "confidence_level": "HIGH",
        "evidence_source": "pharmacology_db",
        "actions": ["Reduce warfarin dose by 25–50%", "Monitor INR every 2–3 days during antifungal course"],
    },
    {
        "drugs": {"warfarin", "amiodarone"},
        "mechanism": "Amiodarone inhibits CYP2C9 and CYP2C19, reducing warfarin metabolism",
        "consequence": "Major bleeding risk from elevated INR",
        "severity": "CRITICAL",
        "interaction_class": "PK",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Reduce warfarin dose by 30–50%", "Increase INR monitoring frequency", "Effect may persist weeks after amiodarone cessation"],
    },
    {
        "drugs": {"warfarin", "metronidazole"},
        "mechanism": "Metronidazole inhibits CYP2C9 and CYP3A4, elevating warfarin levels",
        "consequence": "Major bleeding risk from elevated INR",
        "severity": "CRITICAL",
        "interaction_class": "PK",
        "confidence_level": "HIGH",
        "evidence_source": "pharmacology_db",
        "actions": ["Monitor INR closely during and after metronidazole course", "Consider dose reduction"],
    },
    {
        "drugs": {"warfarin", "ciprofloxacin"},
        "mechanism": "Ciprofloxacin disrupts gut flora reducing vitamin K synthesis and may inhibit CYP1A2",
        "consequence": "INR elevation and bleeding risk",
        "severity": "WARNING",
        "interaction_class": "PK",
        "confidence_level": "MODERATE",
        "evidence_source": "literature",
        "actions": ["Monitor INR within 3–5 days of starting ciprofloxacin"],
    },
    {
        "drugs": {"warfarin", "clarithromycin"},
        "mechanism": "Clarithromycin inhibits CYP3A4 reducing warfarin metabolism",
        "consequence": "Elevated INR and major bleeding risk",
        "severity": "CRITICAL",
        "interaction_class": "PK",
        "confidence_level": "HIGH",
        "evidence_source": "pharmacology_db",
        "actions": ["Monitor INR closely during clarithromycin course", "Consider dose reduction"],
    },
    {
        "drugs": {"fluoxetine", "tramadol"},
        "mechanism": "CYP2D6 inhibition increases tramadol active metabolite; combined serotonin reuptake inhibition",
        "consequence": "Serotonin syndrome and seizures",
        "severity": "CRITICAL",
        "interaction_class": "PK",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid combination", "Use alternative opioid analgesic"],
    },
    {
        "drugs": {"sertraline", "tramadol"},
        "mechanism": "Combined serotonin reuptake inhibition",
        "consequence": "Serotonin syndrome and seizures",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid combination", "Use alternative opioid analgesic"],
    },
    {
        "drugs": {"citalopram", "tramadol"},
        "mechanism": "Combined serotonin reuptake inhibition",
        "consequence": "Serotonin syndrome and seizures",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid combination", "Use alternative opioid analgesic"],
    },
    {
        "drugs": {"escitalopram", "tramadol"},
        "mechanism": "Combined serotonin reuptake inhibition",
        "consequence": "Serotonin syndrome and seizures",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid combination", "Use alternative opioid analgesic"],
    },
    {
        "drugs": {"linezolid", "norepinephrine"},
        "mechanism": "Linezolid inhibits MAO-A; combined with catecholamine causes excessive pressor response",
        "consequence": "Hypertensive crisis — severe systolic hypertension, stroke, intracerebral haemorrhage",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid co-administration", "Switch linezolid to alternative antibiotic if vasopressor required", "If unavoidable: reduce vasopressor dose and monitor MAP continuously"],
    },
    {
        "drugs": {"linezolid", "epinephrine"},
        "mechanism": "Linezolid inhibits MAO-A; combined with catecholamine causes excessive pressor response",
        "consequence": "Hypertensive crisis — severe systolic hypertension and cardiovascular instability",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid co-administration", "Switch linezolid to alternative antibiotic if catecholamine required"],
    },
    {
        "drugs": {"sildenafil", "nitroglycerin"},
        "mechanism": "Combined nitric oxide pathway potentiation causing profound vasodilation",
        "consequence": "Severe hypotension and cardiovascular collapse",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Absolute contraindication — do not co-prescribe", "Withhold nitrates for at least 24 hours after sildenafil (48 hours after tadalafil)"],
    },
    {
        "drugs": {"sildenafil", "isosorbide"},
        "mechanism": "Combined nitric oxide pathway potentiation causing profound vasodilation",
        "consequence": "Severe hypotension and cardiovascular collapse",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Absolute contraindication — do not co-prescribe"],
    },
    {
        "drugs": {"tadalafil", "nitroglycerin"},
        "mechanism": "Combined nitric oxide pathway potentiation causing profound vasodilation",
        "consequence": "Severe hypotension and cardiovascular collapse",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Absolute contraindication — do not co-prescribe", "Withhold nitrates for at least 48 hours after tadalafil"],
    },
    {
        "drugs": {"amiodarone", "ciprofloxacin"},
        "mechanism": "Additive QT interval prolongation via independent cardiac ion channel blockade",
        "consequence": "Torsades de pointes and fatal ventricular arrhythmia",
        "severity": "CRITICAL",
        "interaction_class": "QT",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Obtain baseline ECG and monitor QTc", "Avoid combination if QTc > 480ms", "Use azithromycin or doxycycline as alternative where clinically appropriate"],
    },
    {
        "drugs": {"amiodarone", "levofloxacin"},
        "mechanism": "Additive QT interval prolongation via independent cardiac ion channel blockade",
        "consequence": "Torsades de pointes and fatal ventricular arrhythmia",
        "severity": "CRITICAL",
        "interaction_class": "QT",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Obtain baseline ECG and monitor QTc", "Avoid combination if QTc > 480ms"],
    },
    {
        "drugs": {"amiodarone", "moxifloxacin"},
        "mechanism": "Additive QT interval prolongation via independent cardiac ion channel blockade",
        "consequence": "Torsades de pointes and fatal ventricular arrhythmia",
        "severity": "CRITICAL",
        "interaction_class": "QT",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid combination — moxifloxacin has highest QT risk among fluoroquinolones", "Use alternative antibiotic"],
    },
    {
        "drugs": {"haloperidol", "azithromycin"},
        "mechanism": "Additive QT interval prolongation",
        "consequence": "Torsades de pointes and ventricular arrhythmia",
        "severity": "CRITICAL",
        "interaction_class": "QT",
        "confidence_level": "HIGH",
        "evidence_source": "literature",
        "actions": ["Obtain baseline ECG and monitor QTc", "Avoid combination if QTc > 480ms", "Consider alternative antibiotic or antipsychotic"],
    },
    {
        "drugs": {"haloperidol", "clarithromycin"},
        "mechanism": "Additive QT interval prolongation; clarithromycin also inhibits CYP3A4 increasing haloperidol levels",
        "consequence": "Torsades de pointes and ventricular arrhythmia",
        "severity": "CRITICAL",
        "interaction_class": "QT",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid combination", "Monitor QTc closely if unavoidable", "Consider dose reduction of haloperidol"],
    },
    {
        "drugs": {"haloperidol", "amiodarone"},
        "mechanism": "Combined QT interval prolongation",
        "consequence": "Torsades de pointes and ventricular arrhythmia",
        "severity": "CRITICAL",
        "interaction_class": "QT",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Obtain baseline ECG and monitor QTc", "Avoid combination if QTc > 500ms", "Consider alternative antipsychotic"],
    },
    {
        "drugs": {"vancomycin", "piperacillin-tazobactam"},
        "mechanism": "Synergistic nephrotoxicity — piperacillin-tazobactam increases proximal tubular uptake of vancomycin",
        "consequence": "Acute kidney injury — higher risk than vancomycin monotherapy",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "literature",
        "actions": ["Monitor renal function and vancomycin levels daily", "Consider AUC-guided vancomycin dosing", "Reassess combination after 48–72 hours", "Consider alternative beta-lactam if renal function deteriorates"],
    },
    {
        "drugs": {"lisinopril", "losartan"},
        "mechanism": "Dual renin-angiotensin-aldosterone system blockade",
        "consequence": "Acute kidney injury, hyperkalaemia, and hypotension — triple whammy when combined with NSAID",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid ACEi + ARB dual blockade", "Monitor renal function and electrolytes closely if prescribed", "Use with extreme caution in elderly or CKD patients"],
    },
    {
        "drugs": {"lisinopril", "ibuprofen"},
        "mechanism": "NSAID reduces renal prostaglandins; ACEi reduces efferent arteriolar tone — synergistic renal hypoperfusion",
        "consequence": "Acute kidney injury — triple whammy nephrotoxicity",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid NSAIDs in patients on ACE inhibitors", "Use paracetamol for analgesia", "Monitor renal function if combination is unavoidable"],
    },
    {
        "drugs": {"ramipril", "ibuprofen"},
        "mechanism": "NSAID reduces renal prostaglandins; ACEi reduces efferent arteriolar tone — synergistic renal hypoperfusion",
        "consequence": "Acute kidney injury — triple whammy nephrotoxicity",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid NSAIDs in patients on ACE inhibitors", "Use paracetamol for analgesia"],
    },
    {
        "drugs": {"losartan", "ibuprofen"},
        "mechanism": "NSAID reduces renal prostaglandins; ARB reduces efferent arteriolar tone — synergistic renal hypoperfusion",
        "consequence": "Acute kidney injury — triple whammy nephrotoxicity",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid NSAIDs in patients on ARBs", "Use paracetamol for analgesia"],
    },
    {
        "drugs": {"meropenem", "valproate"},
        "mechanism": "Carbapenem impairs valproate intestinal absorption and increases valproate glucuronidation",
        "consequence": "Subtherapeutic valproate levels and breakthrough seizures",
        "severity": "CRITICAL",
        "interaction_class": "PK",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid combination — consider alternative antibiotic", "If unavoidable: switch to alternative antiepileptic (e.g. levetiracetam)", "Monitor valproate levels closely — levels may drop > 50%"],
    },
    {
        "drugs": {"imipenem", "valproate"},
        "mechanism": "Carbapenem impairs valproate intestinal absorption and increases valproate glucuronidation",
        "consequence": "Subtherapeutic valproate levels and breakthrough seizures",
        "severity": "CRITICAL",
        "interaction_class": "PK",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid combination — consider alternative antibiotic", "If unavoidable: switch to alternative antiepileptic", "Monitor valproate levels closely"],
    },
    {
        "drugs": {"heparin", "abciximab"},
        "mechanism": "Additive anticoagulation and platelet inhibition from GP IIb/IIIa blockade",
        "consequence": "Major bleeding risk from dual haemostatic blockade",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Use only under cardiology or interventional specialist guidance", "Monitor ACT/aPTT closely", "Reduce heparin dose per protocol when GP IIb/IIIa inhibitor is added"],
    },
    {
        "drugs": {"heparin", "eptifibatide"},
        "mechanism": "Additive anticoagulation and platelet inhibition from GP IIb/IIIa blockade",
        "consequence": "Major bleeding risk from dual haemostatic blockade",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Use only under cardiology specialist guidance", "Monitor ACT/aPTT closely"],
    },
    {
        "drugs": {"apixaban", "aspirin"},
        "mechanism": "DOAC anticoagulation combined with antiplatelet therapy — additive haemostatic blockade",
        "consequence": "Major bleeding risk — GI haemorrhage and intracranial bleeding",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Review indication for dual therapy", "Limit duration of combination therapy", "Use lowest effective aspirin dose if combination is essential", "Consider PPI gastroprotection"],
    },
    {
        "drugs": {"rivaroxaban", "aspirin"},
        "mechanism": "DOAC anticoagulation combined with antiplatelet therapy — additive haemostatic blockade",
        "consequence": "Major bleeding risk — GI haemorrhage and intracranial bleeding",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Review indication for dual therapy", "Limit duration to minimum necessary", "Add PPI gastroprotection"],
    },
    {
        "drugs": {"dabigatran", "aspirin"},
        "mechanism": "DOAC anticoagulation combined with antiplatelet therapy",
        "consequence": "Major bleeding risk",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Review indication", "Limit combination duration", "Add PPI gastroprotection"],
    },
    {
        "drugs": {"digoxin", "amiodarone"},
        "mechanism": "Amiodarone inhibits P-glycoprotein, increasing digoxin plasma levels",
        "consequence": "Digoxin toxicity — nausea, arrhythmia, heart block",
        "severity": "CRITICAL",
        "interaction_class": "PK",
        "confidence_level": "HIGH",
        "evidence_source": "pharmacology_db",
        "actions": ["Reduce digoxin dose by 50%", "Monitor digoxin levels and ECG", "Monitor renal function"],
    },
    {
        "drugs": {"digoxin", "verapamil"},
        "mechanism": "Verapamil reduces renal and non-renal digoxin clearance",
        "consequence": "Digoxin toxicity and arrhythmia",
        "severity": "CRITICAL",
        "interaction_class": "PK",
        "confidence_level": "HIGH",
        "evidence_source": "pharmacology_db",
        "actions": ["Reduce digoxin dose", "Monitor digoxin levels and ECG regularly"],
    },
    {
        "drugs": {"metformin", "contrast"},
        "mechanism": "IV contrast can cause acute kidney injury reducing metformin excretion",
        "consequence": "Lactic acidosis from metformin accumulation",
        "severity": "WARNING",
        "interaction_class": "PK",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Withhold metformin 48 hours before and after IV contrast", "Reassess renal function before restarting"],
    },
    {
        "drugs": {"lisinopril", "spironolactone"},
        "mechanism": "Combined suppression of aldosterone and potassium excretion",
        "consequence": "Severe hyperkalaemia — cardiac arrhythmia and arrest",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Monitor potassium and renal function closely", "Avoid in patients with CKD or baseline hyperkalaemia"],
    },
    {
        "drugs": {"ramipril", "spironolactone"},
        "mechanism": "Combined suppression of aldosterone and potassium excretion",
        "consequence": "Severe hyperkalaemia — cardiac arrhythmia and arrest",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Monitor potassium and renal function closely", "Avoid in CKD"],
    },
    {
        "drugs": {"lithium", "ibuprofen"},
        "mechanism": "NSAIDs reduce renal prostaglandin synthesis, decreasing lithium clearance",
        "consequence": "Lithium toxicity — tremor, confusion, seizures, renal failure",
        "severity": "CRITICAL",
        "interaction_class": "PK",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid NSAIDs in patients on lithium", "Use paracetamol for analgesia", "Monitor lithium levels urgently if combination used"],
    },
    {
        "drugs": {"lithium", "naproxen"},
        "mechanism": "NSAIDs reduce renal prostaglandin synthesis, decreasing lithium clearance",
        "consequence": "Lithium toxicity — tremor, confusion, seizures, renal failure",
        "severity": "CRITICAL",
        "interaction_class": "PK",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid NSAIDs in patients on lithium", "Use paracetamol for analgesia"],
    },
    {
        "drugs": {"methotrexate", "ibuprofen"},
        "mechanism": "NSAIDs reduce renal clearance of methotrexate and displace it from protein binding",
        "consequence": "Methotrexate toxicity — pancytopenia and organ failure",
        "severity": "CRITICAL",
        "interaction_class": "PK",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid NSAIDs with methotrexate", "Monitor FBC and LFTs urgently"],
    },
    {
        "drugs": {"methotrexate", "naproxen"},
        "mechanism": "NSAIDs reduce renal clearance of methotrexate",
        "consequence": "Methotrexate toxicity — pancytopenia and organ failure",
        "severity": "CRITICAL",
        "interaction_class": "PK",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Avoid NSAIDs with methotrexate", "Monitor FBC and LFTs urgently"],
    },
    {
        "drugs": {"gentamicin", "vancomycin"},
        "mechanism": "Additive nephrotoxicity and ototoxicity",
        "consequence": "Acute kidney injury and hearing loss",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Monitor renal function daily", "Check therapeutic drug levels", "Reduce dose or frequency in renal impairment"],
    },
    {
        "drugs": {"gentamicin", "furosemide"},
        "mechanism": "Furosemide increases aminoglycoside nephrotoxicity and ototoxicity",
        "consequence": "Acute kidney injury and irreversible hearing loss",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "literature",
        "actions": ["Monitor renal function and audiometry", "Ensure adequate hydration"],
    },
    {
        "drugs": {"clopidogrel", "omeprazole"},
        "mechanism": "Omeprazole inhibits CYP2C19, reducing clopidogrel activation",
        "consequence": "Reduced antiplatelet efficacy — increased risk of thrombosis",
        "severity": "WARNING",
        "interaction_class": "PK",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Prefer pantoprazole over omeprazole in patients on clopidogrel"],
    },
    {
        "drugs": {"clopidogrel", "esomeprazole"},
        "mechanism": "Esomeprazole inhibits CYP2C19, reducing clopidogrel activation",
        "consequence": "Reduced antiplatelet efficacy — increased risk of thrombosis",
        "severity": "WARNING",
        "interaction_class": "PK",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Prefer pantoprazole over esomeprazole in patients on clopidogrel"],
    },
    {
        "drugs": {"insulin", "propranolol"},
        "mechanism": "Beta blockers mask tachycardia and other adrenergic hypoglycaemia symptoms; propranolol may also prolong hypoglycaemia",
        "consequence": "Hypoglycaemia may be masked and prolonged",
        "severity": "WARNING",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Counsel patient on alternative hypoglycaemia symptoms (sweating, pallor)", "Monitor blood glucose more frequently"],
    },
    {
        "drugs": {"insulin", "metoprolol"},
        "mechanism": "Beta-1 selective blocker partially masks adrenergic hypoglycaemia symptoms",
        "consequence": "Hypoglycaemia may be partially masked",
        "severity": "WARNING",
        "interaction_class": "PD",
        "confidence_level": "MODERATE",
        "evidence_source": "guideline",
        "actions": ["Counsel patient on sweating as alternative hypoglycaemia symptom", "Monitor blood glucose more frequently"],
    },
    {
        "drugs": {"heparin", "enoxaparin"},
        "mechanism": "Therapeutic duplication — dual anticoagulation without additive clinical benefit",
        "consequence": "Major bleeding risk",
        "severity": "CRITICAL",
        "interaction_class": "PD",
        "confidence_level": "HIGH",
        "evidence_source": "guideline",
        "actions": ["Use only one anticoagulant", "Review therapeutic intent and select appropriate agent"],
    },
    {
        "drugs": {"phenytoin", "fluconazole"},
        "mechanism": "Fluconazole inhibits CYP2C9 reducing phenytoin metabolism",
        "consequence": "Phenytoin toxicity — ataxia, nystagmus, and seizures",
        "severity": "CRITICAL",
        "interaction_class": "PK",
        "confidence_level": "HIGH",
        "evidence_source": "pharmacology_db",
        "actions": ["Monitor phenytoin levels closely", "Reduce phenytoin dose if levels are elevated"],
    },
]

ANTICOAGULANTS: Set[str] = {
    "warfarin",
    "heparin",
    "enoxaparin",
    "dalteparin",
    "tinzaparin",
    "fondaparinux",
    "dabigatran",
    "rivaroxaban",
    "apixaban",
    "edoxaban",
}

ANTIMICROBIAL_COVERAGE_CLASSES: Dict[str, Set[str]] = {
    "fluoroquinolone": {"ciprofloxacin", "levofloxacin", "moxifloxacin", "norfloxacin", "ofloxacin"},
    "macrolide": {"azithromycin", "clarithromycin", "erythromycin", "roxithromycin"},
    "penicillin": {"amoxicillin", "ampicillin", "piperacillin", "flucloxacillin", "benzylpenicillin", "phenoxymethylpenicillin"},
    "carbapenem": {"meropenem", "imipenem", "ertapenem", "doripenem"},
    "cephalosporin": {"cephalexin", "cefazolin", "ceftriaxone", "cefepime", "cefuroxime", "cefoxitin"},
    "tetracycline": {"doxycycline", "tetracycline", "minocycline"},
    "glycopeptide": {"vancomycin", "teicoplanin"},
}

SEDATIVES: Set[str] = {
    "midazolam",
    "diazepam",
    "lorazepam",
    "clonazepam",
    "alprazolam",
    "temazepam",
    "nitrazepam",
    "oxazepam",
    "propofol",
    "ketamine",
    "dexmedetomidine",
    "clonidine",
}

OPIOIDS: Set[str] = {
    "morphine",
    "fentanyl",
    "oxycodone",
    "hydromorphone",
    "codeine",
    "tramadol",
    "buprenorphine",
    "methadone",
    "pethidine",
    "tapentadol",
}

APINCH_CLASSES: Dict[str, Set[str]] = {
    "Anti-infective (aminoglycoside)": {"gentamicin", "tobramycin", "amikacin", "neomycin"},
    "Anti-infective (glycopeptide)": {"vancomycin", "teicoplanin"},
    "Potassium / electrolyte concentrate": {"potassium chloride", "potassium phosphate", "hypertonic saline"},
    "Insulin": {"insulin"},
    "Narcotic / opioid": {"morphine", "fentanyl", "oxycodone", "hydromorphone", "methadone", "pethidine", "buprenorphine"},
    "Chemotherapy": {"methotrexate", "cyclophosphamide", "vincristine", "doxorubicin", "cisplatin", "carboplatin", "fluorouracil", "capecitabine"},
    "Heparin / anticoagulant": {"heparin", "enoxaparin", "warfarin", "dabigatran", "rivaroxaban", "apixaban", "fondaparinux"},
}

ABSOLUTE_CONTRAINDICATIONS: List[Dict] = [
    {
        "drug": "metformin",
        "conditions": {"renal failure", "ckd stage 4", "ckd stage 5", "egfr < 30", "contrast nephropathy"},
        "risk": "Lactic acidosis from metformin accumulation in renal impairment",
        "action": "Withhold metformin; assess renal function before restarting",
    },
    {
        "drug": "ibuprofen",
        "conditions": {"peptic ulcer", "gi bleed", "gastric ulcer", "duodenal ulcer"},
        "risk": "GI haemorrhage and ulcer perforation",
        "action": "Avoid NSAIDs; use paracetamol; add PPI if NSAID is essential",
    },
    {
        "drug": "naproxen",
        "conditions": {"peptic ulcer", "gi bleed", "gastric ulcer", "duodenal ulcer"},
        "risk": "GI haemorrhage and ulcer perforation",
        "action": "Avoid NSAIDs; use paracetamol; add PPI if NSAID is essential",
    },
    {
        "drug": "warfarin",
        "conditions": {"active bleeding", "intracranial haemorrhage", "haemorrhagic stroke"},
        "risk": "Catastrophic haemorrhage extension",
        "action": "Withhold warfarin immediately; seek haematology review",
    },
    {
        "drug": "lisinopril",
        "conditions": {"angioedema", "pregnancy", "bilateral renal artery stenosis"},
        "risk": "Angioedema recurrence, foetal renal damage, or acute renal failure",
        "action": "Avoid ACE inhibitors; use alternative antihypertensive",
    },
    {
        "drug": "ramipril",
        "conditions": {"angioedema", "pregnancy", "bilateral renal artery stenosis"},
        "risk": "Angioedema recurrence, foetal renal damage, or acute renal failure",
        "action": "Avoid ACE inhibitors; use alternative antihypertensive",
    },
    {
        "drug": "propranolol",
        "conditions": {"severe asthma", "acute bronchospasm", "second degree heart block", "third degree heart block"},
        "risk": "Severe bronchoconstriction or complete heart block",
        "action": "Avoid non-selective beta blockers; use alternative",
    },
    {
        "drug": "metoprolol",
        "conditions": {"second degree heart block", "third degree heart block", "severe bradycardia"},
        "risk": "Complete heart block or haemodynamically significant bradycardia",
        "action": "Withhold beta blocker; obtain cardiology review",
    },
]
