/*
  # MediRangeX Initial Schema

  ## Overview
  Creates the full database schema for the MediRangeX AI healthcare intelligence platform.

  ## New Tables

  ### roles
  - Lookup table for user role types (clinician, admin, pharmacist, data_scientist)
  - id: UUID primary key
  - name: enum role value (unique)
  - description: human-readable description

  ### users
  - Platform users (clinicians, admins, pharmacists, data scientists)
  - Linked to a role via role_id foreign key
  - Stores hashed_password, email, full_name, is_active

  ### patients
  - Core patient demographics and context
  - patient_id: UUID primary key
  - mrn: medical record number (unique index)
  - age, sex, weight_kg, height_cm: clinical measurements
  - admission_time, care_setting: context fields (ICU/Ward/ED)

  ### encounters
  - Clinical encounter records tied to a patient
  - Tracks encounter type, status, start/end times, chief complaint

  ### observations
  - Clinical measurements/results (vitals, labs, assessments)
  - Supports LOINC code, numeric/string values, units

  ### medications
  - Medication orders per patient
  - Supports RxNorm codes, dose, route, frequency, status

  ### prediction_logs
  - Audit trail for all AI model predictions
  - Tracks model_type, input/output payloads, confidence_score, latency

  ### alert_logs
  - Clinical alerts generated by the platform
  - Tracks severity, status, acknowledgement, resolution

  ## Security
  - RLS enabled on all tables
  - All policies require authenticated access
  - Users can only read their own user record (admin sees all)
  - Patient data accessible to all authenticated users (clinical setting)

  ## Notes
  1. All tables use UUID primary keys
  2. All tables include created_at / updated_at timestamps
  3. Enums are created as PostgreSQL ENUM types
*/

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TYPE role_enum AS ENUM ('clinician', 'admin', 'pharmacist', 'data_scientist');
CREATE TYPE sex_enum AS ENUM ('male', 'female', 'other', 'unknown');
CREATE TYPE care_setting_enum AS ENUM ('ICU', 'Ward', 'ED');
CREATE TYPE encounter_status_enum AS ENUM ('active', 'completed', 'cancelled');
CREATE TYPE medication_status_enum AS ENUM ('active', 'completed', 'discontinued', 'on_hold');
CREATE TYPE alert_severity_enum AS ENUM ('info', 'warning', 'critical');
CREATE TYPE alert_status_enum AS ENUM ('open', 'acknowledged', 'resolved');

CREATE TABLE IF NOT EXISTS roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name role_enum UNIQUE NOT NULL,
  description VARCHAR(255),
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255) UNIQUE NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  hashed_password VARCHAR(255) NOT NULL,
  is_active BOOLEAN DEFAULT true NOT NULL,
  role_id UUID NOT NULL REFERENCES roles(id),
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

CREATE TABLE IF NOT EXISTS patients (
  patient_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  mrn VARCHAR(64) UNIQUE NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  date_of_birth TIMESTAMPTZ,
  age INTEGER,
  sex sex_enum NOT NULL,
  weight_kg FLOAT,
  height_cm FLOAT,
  admission_time TIMESTAMPTZ,
  care_setting care_setting_enum,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_patients_mrn ON patients(mrn);

CREATE TABLE IF NOT EXISTS encounters (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id UUID NOT NULL REFERENCES patients(patient_id),
  encounter_type VARCHAR(64) NOT NULL,
  status encounter_status_enum DEFAULT 'active' NOT NULL,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ,
  chief_complaint TEXT,
  discharge_summary TEXT,
  attending_clinician_id UUID REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_encounters_patient_id ON encounters(patient_id);

CREATE TABLE IF NOT EXISTS observations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id UUID NOT NULL REFERENCES patients(patient_id),
  encounter_id UUID REFERENCES encounters(id),
  loinc_code VARCHAR(32),
  display_name VARCHAR(255) NOT NULL,
  value_numeric FLOAT,
  value_string VARCHAR(512),
  unit VARCHAR(64),
  observed_at TIMESTAMPTZ NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_observations_patient_id ON observations(patient_id);
CREATE INDEX IF NOT EXISTS idx_observations_encounter_id ON observations(encounter_id);
CREATE INDEX IF NOT EXISTS idx_observations_loinc_code ON observations(loinc_code);

CREATE TABLE IF NOT EXISTS medications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id UUID NOT NULL REFERENCES patients(patient_id),
  encounter_id UUID REFERENCES encounters(id),
  rxnorm_code VARCHAR(32),
  drug_name VARCHAR(255) NOT NULL,
  dose VARCHAR(64),
  route VARCHAR(64),
  frequency VARCHAR(64),
  start_date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ,
  status medication_status_enum DEFAULT 'active' NOT NULL,
  prescriber_id UUID REFERENCES users(id),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_medications_patient_id ON medications(patient_id);
CREATE INDEX IF NOT EXISTS idx_medications_rxnorm_code ON medications(rxnorm_code);

CREATE TABLE IF NOT EXISTS prediction_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id UUID REFERENCES patients(patient_id),
  user_id UUID REFERENCES users(id),
  model_type VARCHAR(128) NOT NULL,
  model_version VARCHAR(32),
  input_payload JSONB,
  output_payload JSONB,
  confidence_score FLOAT,
  latency_ms FLOAT,
  status VARCHAR(32) DEFAULT 'success' NOT NULL,
  error_message TEXT,
  requested_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_prediction_logs_patient_id ON prediction_logs(patient_id);
CREATE INDEX IF NOT EXISTS idx_prediction_logs_user_id ON prediction_logs(user_id);

CREATE TABLE IF NOT EXISTS alert_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id UUID REFERENCES patients(patient_id),
  user_id UUID REFERENCES users(id),
  alert_type VARCHAR(128) NOT NULL,
  severity alert_severity_enum DEFAULT 'info' NOT NULL,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  status alert_status_enum DEFAULT 'open' NOT NULL,
  acknowledged_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ,
  acknowledged_by_id UUID REFERENCES users(id),
  triggered_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_alert_logs_patient_id ON alert_logs(patient_id);
CREATE INDEX IF NOT EXISTS idx_alert_logs_user_id ON alert_logs(user_id);

ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE encounters ENABLE ROW LEVEL SECURITY;
ALTER TABLE observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE medications ENABLE ROW LEVEL SECURITY;
ALTER TABLE prediction_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE alert_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read roles"
  ON roles FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can read own user record"
  ON users FOR SELECT
  TO authenticated
  USING (auth.uid() = id);

CREATE POLICY "Authenticated users can update own user record"
  ON users FOR UPDATE
  TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Authenticated users can read patients"
  ON patients FOR SELECT
  TO authenticated
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can insert patients"
  ON patients FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can update patients"
  ON patients FOR UPDATE
  TO authenticated
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can read encounters"
  ON encounters FOR SELECT
  TO authenticated
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can insert encounters"
  ON encounters FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can read observations"
  ON observations FOR SELECT
  TO authenticated
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can insert observations"
  ON observations FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can read medications"
  ON medications FOR SELECT
  TO authenticated
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can insert medications"
  ON medications FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can read own prediction logs"
  ON prediction_logs FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Authenticated users can insert prediction logs"
  ON prediction_logs FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Authenticated users can read own alert logs"
  ON alert_logs FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Authenticated users can insert alert logs"
  ON alert_logs FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

INSERT INTO roles (name, description) VALUES
  ('clinician', 'Clinical staff with patient care responsibilities'),
  ('admin', 'Platform administrator with full system access'),
  ('pharmacist', 'Pharmacy staff managing medication orders'),
  ('data_scientist', 'Data science team for model management and forecasting')
ON CONFLICT (name) DO NOTHING;
